services:
  payment-service:
    image: pick2me-payment-service:1.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ../Pick2Me-Shared/dist:/app/node_modules/@pick2me/shared/dist
     - ../Pick2Me-Shared/package.json:/app/node_modules/@pick2me/shared/package.json
    container_name: payment-service
    env_file:
      - .env
    ports:
      - "3004:3004"
    restart: unless-stopped
    networks:
      - miro-backend

networks:
  miro-backend:
    external: true
